# Generated by Django 4.2.7 on 2023-11-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='Title_EN', max_length=255)),
                ('sentiment_score', models.FloatField(blank=True, db_column='SentimentScore', null=True)),
                ('source', models.CharField(db_column='Source', max_length=100)),
                ('url', models.URLField(db_column='URL')),
            ],
            options={
                'db_table': 'Articles',
                'managed': False,
            },
        ),
    ]
