# Generated by Django 4.2.7 on 2023-11-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewAvgSentimentBySource',
            fields=[
                ('source', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('avgsentiment', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'View_AvgSentimentBySource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewNationalMood',
            fields=[
                ('nationalmood', models.DecimalField(decimal_places=2, max_digits=5, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'View_NationalMood',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewSentimentHeatmap',
            fields=[
                ('source', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('verynegative', models.IntegerField()),
                ('negative', models.IntegerField()),
                ('neutral', models.IntegerField()),
                ('positive', models.IntegerField()),
                ('verypositive', models.IntegerField()),
            ],
            options={
                'db_table': 'View_SentimentHeatmap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewSentimentOverTime',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('avgsentiment', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'View_SentimentOverTime',
                'managed': False,
            },
        ),
    ]
